name: Deploy to prod

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Build site
        uses: gha-utilities/jekyll-build@v0.0.2
        with:
          source: .
          destination: ./deploy
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: ./deploy

      - name: Copy to FTP
        uses: sebastianpopp/git-ftp-action@releases/v2
        with: 
          url: "ftp://s1.hostpark.pl:21/greenfieldconf.pl-new"
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWD }}
          syncroot: ./deploy
          
      - name: Purge CloudFlare cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
