name: Deploy to prod

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Build site
        uses: gha-utilities/jekyll-build@v0.0.2
        with:
          source: .
          destination: ./deploy
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: ./deploy

      - name: Copy to FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with: 
          host: "ftp://s1.hostpark.pl:21"
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWD }}
          localDir: ./deploy
          remoteDir: greenfieldconf.pl/public_html
          
      - name: Purge CloudFlare cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          
          
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: www
          LACK_MESSAGE: 'Greenfieldconf www deployed :rocket:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
